### ISSUE TITLE
Pending Issue in line-charts

### ISSUE THREAD

**Issue by aakanksha023** [UBC-MDS/DSCI_532_L02_Group212_SocialMobilityProject#23]
- Remove title "child"
- Remove repetition on X-axis
- Increase font size and bold plot header(s) - "all/daughter/son"
- Improve legend

**Comment by MrThomasPin** [comment]
The child has been removed 
to my best knowledge no way to fix the x repetition, increase font size

**Comment by hwilliams10** [comment]
Increased font size for facet label, and increased legend size

**Comment by aakanksha023** [comment]
I'm good with it.
@hwilliams10 - You can close this issue if you are okay with the X axis labels.
