### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by braydentang1** [UBC-MDS/DSCI_532_L02_Group212_SocialMobilityProject#43]
- Education Mobility Index: Perhaps defining what it stands for/explain what this is in more detail
- Ability to filter the bar chart to say, top 10 countries or specific countries selected
- Missing data not showing up on the map. Perhaps make this more obvious?
- Difficult to select specific countries via. the map since some of the countries are small (like in Europe). Perhaps faceting by continent could be more useful so that the map zooms in on that particular area. 

Overall, I really enjoyed the app. Awesome work Group 212!

**Comment by aakanksha023** [comment]
Merged into [this issue](https://github.com/UBC-MDS/DSCI_532_L02_Group212_SocialMobilityProject/issues/46)
