### ISSUE TITLE
Feedback notes on Visualizing Global Education Opportunity

### ISSUE THREAD

**Issue by jsleslie** [UBC-MDS/DSCI_532_L02_Group212_SocialMobilityProject#44]
1. Social mobility index is an interesting feature worth exploring - liked the stab at the US 

2. Change the map legend title from the year to 'EMI'

3. Functionality to click on a country from the map or from the ranking chart is nice have. Perhaps moving the sentence on shift click to under the generation selection component would help direct users when there are ready to play around with the maps

4. Bottom section allows for comparisons between countries or groups - maybe bold this part?

5. Time series plot with the vertical line and data labels is quite useful

6. Question - can you zoom in on the map to see smaller countries?

**Comment by aakanksha023** [comment]
Merged into [this issue](https://github.com/UBC-MDS/DSCI_532_L02_Group212_SocialMobilityProject/issues/46)
