### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by vanandsh** [UBC-MDS/DSCI_532_L02_Group212_SocialMobilityProject#45]
- Too much text in the beginning
- The functionality of shift + click for multiple countries was not obvious
- Colour contrast could be better
- The index is always a reference, base reference was not clear
- EMI was used in the Y-axis for line plots. The abbreviation was not clear.

**Comment by aakanksha023** [comment]
Merged into [this issue](https://github.com/UBC-MDS/DSCI_532_L02_Group212_SocialMobilityProject/issues/46)
